// AUTO-GENERATED by scripts/build-selector-index.mjs — do not edit by hand.
// Regenerate with: yarn picker:index
//
// Consumed by the dev-only DOM picker to report which extension code already
// targets a picked element. Not referenced by any shipped feature.

export interface SelectorUsage {
  /** The literal as written in source. */
  selector: string;
  /** Repo-relative path. */
  file: string;
  line: number;
  /** Which function it was passed to. */
  fn: string;
}

/** When this index was generated (ms since epoch). */
export const GENERATED_AT = 1788439561013;

/** Newest mtime among the source files scanned, for staleness detection. */
export const NEWEST_SOURCE_AT = 1788439016077;

export const SELECTOR_USAGES: SelectorUsage[] = [
  {
    "selector": "[data-id]",
    "file": "components/Settings/Animations.vue",
    "line": 573,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#root",
    "file": "entrypoints/content/index.ts",
    "line": 60,
    "fn": "querySelector"
  },
  {
    "selector": "body",
    "file": "entrypoints/content/index.ts",
    "line": 64,
    "fn": "querySelector"
  },
  {
    "selector": "svg",
    "file": "entrypoints/content/v2-menu.ts",
    "line": 55,
    "fn": "querySelector"
  },
  {
    "selector": "canvas",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 99,
    "fn": "querySelector"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 34,
    "fn": "querySelector"
  },
  {
    "selector": "main",
    "file": "entrypoints/match.content/button-countdown.ts",
    "line": 80,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/caller.ts",
    "line": 256,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/caller.ts",
    "line": 261,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/caller.ts",
    "line": 329,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification-close",
    "file": "entrypoints/match.content/caller.ts",
    "line": 349,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/caller.ts",
    "line": 382,
    "fn": "querySelector"
  },
  {
    "selector": "main",
    "file": "entrypoints/match.content/checkout-guide.ts",
    "line": 156,
    "fn": "closest"
  },
  {
    "selector": "main",
    "file": "entrypoints/match.content/gotcha.ts",
    "line": 134,
    "fn": "closest"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 380,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 385,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 453,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification-close",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 473,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 506,
    "fn": "querySelector"
  },
  {
    "selector": "svg",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 693,
    "fn": "querySelectorAll"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 858,
    "fn": "querySelector"
  },
  {
    "selector": "label",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 178,
    "fn": "querySelector"
  },
  {
    "selector": "label",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 224,
    "fn": "querySelector"
  },
  {
    "selector": "input",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 231,
    "fn": "querySelectorAll"
  },
  {
    "selector": "[id]",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 232,
    "fn": "querySelectorAll"
  },
  {
    "selector": "[aria-labelledby]",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 233,
    "fn": "querySelectorAll"
  },
  {
    "selector": "label",
    "file": "utils/quiet-own-darts-switch.ts",
    "line": 235,
    "fn": "querySelector"
  },
  {
    "selector": "[data-slot]",
    "file": "utils/selectors.ts",
    "line": 64,
    "fn": "querySelector"
  },
  {
    "selector": "[class*='chakra-']",
    "file": "utils/selectors.ts",
    "line": 65,
    "fn": "querySelector"
  },
  {
    "selector": "Lobby",
    "file": "utils/selectors.ts",
    "line": 254,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "img[src^=\\\"blob:\\\"]",
    "file": "utils/websocket-helpers.ts",
    "line": 343,
    "fn": "querySelectorAll"
  }
];
