// AUTO-GENERATED by scripts/build-selector-index.mjs — do not edit by hand.
// Regenerate with: yarn picker:index
//
// Consumed by the dev-only DOM picker to report which extension code already
// targets a picked element. Not referenced by any shipped feature.

export interface SelectorUsage {
  /** The literal as written in source. */
  selector: string;
  /** Repo-relative path. */
  file: string;
  line: number;
  /** Which function it was passed to. */
  fn: string;
}

/** When this index was generated (ms since epoch). */
export const GENERATED_AT = 1786725887385;

/** Newest mtime among the source files scanned, for staleness detection. */
export const NEWEST_SOURCE_AT = 1786725266616;

export const SELECTOR_USAGES: SelectorUsage[] = [
  {
    "selector": "html",
    "file": "components/PageConfig.vue",
    "line": 345,
    "fn": "querySelector"
  },
  {
    "selector": "[data-id]",
    "file": "components/Settings/Animations.vue",
    "line": 577,
    "fn": "querySelectorAll"
  },
  {
    "selector": "autodarts-tools-external-boards",
    "file": "entrypoints/boards.content/index.ts",
    "line": 24,
    "fn": "querySelector"
  },
  {
    "selector": "My Boards",
    "file": "entrypoints/boards.content/index.ts",
    "line": 40,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "#root",
    "file": "entrypoints/content/index.ts",
    "line": 49,
    "fn": "querySelector"
  },
  {
    "selector": "body",
    "file": "entrypoints/content/index.ts",
    "line": 53,
    "fn": "querySelector"
  },
  {
    "selector": "svg",
    "file": "entrypoints/content/v2-menu.ts",
    "line": 55,
    "fn": "querySelector"
  },
  {
    "selector": "button",
    "file": "entrypoints/lobbynew.content/index.ts",
    "line": 29,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Public",
    "file": "entrypoints/lobbynew.content/index.ts",
    "line": 29,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "button",
    "file": "entrypoints/lobbynew.content/index.ts",
    "line": 30,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Private",
    "file": "entrypoints/lobbynew.content/index.ts",
    "line": 30,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Invite friends",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 11,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Nodig vrienden uit",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 11,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Freunde einladen",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 11,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": ".ad-ext_qr-code-wrapper",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 37,
    "fn": "querySelector"
  },
  {
    "selector": "canvas",
    "file": "entrypoints/lobbynew.content/qr-code-tournament.ts",
    "line": 64,
    "fn": "querySelector"
  },
  {
    "selector": "p",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 8,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "or share link:",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 8,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Link teilen:",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 8,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Deel link:",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 8,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "input[placeholder=\\\"Lobby invite url\\\"]",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 11,
    "fn": "querySelector"
  },
  {
    "selector": "canvas",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 29,
    "fn": "querySelector"
  },
  {
    "selector": "canvas",
    "file": "entrypoints/lobbynew.content/qr-code.ts",
    "line": 41,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/Animations.vue",
    "line": 115,
    "fn": "querySelector"
  },
  {
    "selector": ".showAnimations",
    "file": "entrypoints/match.content/Animations.vue",
    "line": 115,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-player-display",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 7,
    "fn": "waitForElement"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 18,
    "fn": "querySelector"
  },
  {
    "selector": "#adt-fullscreen-toggle",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 23,
    "fn": "querySelector"
  },
  {
    "selector": "svg",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 42,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 48,
    "fn": "querySelector"
  },
  {
    "selector": "div:last-of-type",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 49,
    "fn": "querySelector"
  },
  {
    "selector": "ul",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 51,
    "fn": "querySelector"
  },
  {
    "selector": "#adt-fullscreen-toggle",
    "file": "entrypoints/match.content/automatic-fullscreen.ts",
    "line": 123,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/automatic-next-leg.ts",
    "line": 25,
    "fn": "waitForElement"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/automatic-next-leg.ts",
    "line": 37,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Next Leg",
    "file": "entrypoints/match.content/automatic-next-leg.ts",
    "line": 37,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Nächstes Leg",
    "file": "entrypoints/match.content/automatic-next-leg.ts",
    "line": 37,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Volgende leg",
    "file": "entrypoints/match.content/automatic-next-leg.ts",
    "line": 37,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/caller.ts",
    "line": 243,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/caller.ts",
    "line": 248,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/caller.ts",
    "line": 316,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification-close",
    "file": "entrypoints/match.content/caller.ts",
    "line": 336,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/caller.ts",
    "line": 369,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-player-display",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 18,
    "fn": "waitForElement"
  },
  {
    "selector": ".ad-ext-player",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 19,
    "fn": "querySelectorAll"
  },
  {
    "selector": "body",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 21,
    "fn": "querySelector"
  },
  {
    "selector": "a",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 26,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 29,
    "fn": "querySelector"
  },
  {
    "selector": "p",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 33,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext-player-name",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 43,
    "fn": "querySelectorAll"
  },
  {
    "selector": "body",
    "file": "entrypoints/match.content/color-change.ts",
    "line": 60,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/enhanced-scoring-display.ts",
    "line": 13,
    "fn": "waitForElement"
  },
  {
    "selector": "#ad-ext-turn > .ad-ext-turn-throw > p",
    "file": "entrypoints/match.content/enhanced-scoring-display.ts",
    "line": 41,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#ad-ext-turn > .suggestion > p",
    "file": "entrypoints/match.content/enhanced-scoring-display.ts",
    "line": 46,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#adt-menu-hide",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 5,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-player-display",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 8,
    "fn": "waitForElement"
  },
  {
    "selector": "#root > div > div",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 13,
    "fn": "waitForElement"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 18,
    "fn": "querySelector"
  },
  {
    "selector": "svg",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 19,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 34,
    "fn": "querySelector"
  },
  {
    "selector": "div:last-of-type",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 34,
    "fn": "querySelector"
  },
  {
    "selector": "ul",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 34,
    "fn": "querySelector"
  },
  {
    "selector": "#adt-menu-hide",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 59,
    "fn": "querySelector"
  },
  {
    "selector": "#root > div > div",
    "file": "entrypoints/match.content/hide-menu-in-match.ts",
    "line": 63,
    "fn": "querySelector"
  },
  {
    "selector": "Board has no active match",
    "file": "entrypoints/match.content/index.ts",
    "line": 98,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Board hat kein aktives Spiel",
    "file": "entrypoints/match.content/index.ts",
    "line": 98,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Bord heeft geen actieve wedstrijd",
    "file": "entrypoints/match.content/index.ts",
    "line": 98,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Board has no active match",
    "file": "entrypoints/match.content/index.ts",
    "line": 283,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Board hat kein aktives Spiel",
    "file": "entrypoints/match.content/index.ts",
    "line": 283,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Bord heeft geen actieve wedstrijd",
    "file": "entrypoints/match.content/index.ts",
    "line": 283,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "#ad-ext-player-display",
    "file": "entrypoints/match.content/index.ts",
    "line": 346,
    "fn": "waitForElement"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/InstantReplay.vue",
    "line": 210,
    "fn": "querySelector"
  },
  {
    "selector": ".showAnimations",
    "file": "entrypoints/match.content/InstantReplay.vue",
    "line": 210,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 5,
    "fn": "waitForElement"
  },
  {
    "selector": ".ad-ext-player",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 14,
    "fn": "querySelectorAll"
  },
  {
    "selector": ".chakra-stack span",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 15,
    "fn": "querySelectorAll"
  },
  {
    "selector": ".ad-ext-player-name",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 17,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext-player-name",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 18,
    "fn": "closest"
  },
  {
    "selector": "p",
    "file": "entrypoints/match.content/larger-legs-sets.ts",
    "line": 23,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/larger-player-match-data.ts",
    "line": 5,
    "fn": "waitForElement"
  },
  {
    "selector": ".ad-ext-player",
    "file": "entrypoints/match.content/larger-player-match-data.ts",
    "line": 14,
    "fn": "querySelectorAll"
  },
  {
    "selector": "div:last-of-type > p",
    "file": "entrypoints/match.content/larger-player-match-data.ts",
    "line": 15,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/larger-player-names.ts",
    "line": 5,
    "fn": "waitForElement"
  },
  {
    "selector": ".ad-ext-player-name",
    "file": "entrypoints/match.content/larger-player-names.ts",
    "line": 14,
    "fn": "querySelectorAll"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/next-player-on-take-out-stuck.ts",
    "line": 83,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Next",
    "file": "entrypoints/match.content/next-player-on-take-out-stuck.ts",
    "line": 83,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/next-player-on-take-out-stuck.ts",
    "line": 87,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/QuickCorrection.vue",
    "line": 404,
    "fn": "waitForElement"
  },
  {
    "selector": "p > div > div:last-of-type",
    "file": "entrypoints/match.content/QuickCorrection.vue",
    "line": 575,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 385,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 390,
    "fn": "querySelector"
  },
  {
    "selector": "style[data-adt-notification-style]",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 458,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification-close",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 478,
    "fn": "querySelector"
  },
  {
    "selector": ".adt-notification",
    "file": "entrypoints/match.content/sound-fx.ts",
    "line": 511,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 483,
    "fn": "querySelector"
  },
  {
    "selector": "span",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 485,
    "fn": "querySelectorAll"
  },
  {
    "selector": "Live mode",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 499,
    "fn": "querySelector"
  },
  {
    "selector": "Coords mode",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 500,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-player-display",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 511,
    "fn": "querySelector"
  },
  {
    "selector": "#adt-stream-mode-button",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 511,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/StreamingMode.vue",
    "line": 512,
    "fn": "waitForElement"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/Takeout.vue",
    "line": 55,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "Reset",
    "file": "entrypoints/match.content/Takeout.vue",
    "line": 55,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 102,
    "fn": "waitForElement"
  },
  {
    "selector": ".ad-ext-player-score",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 105,
    "fn": "querySelectorAll"
  },
  {
    "selector": ".ad-ext_winner-animation",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 112,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext_winner-score-wrapper",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 115,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext_winner-animation",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 118,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext-player-winner",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 147,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext-player-score",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 148,
    "fn": "querySelector"
  },
  {
    "selector": ".ad-ext_winner-score-wrapper",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 153,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 192,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/winner-animation.ts",
    "line": 219,
    "fn": "waitForElement"
  },
  {
    "selector": "#root .navigation",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 129,
    "fn": "querySelector"
  },
  {
    "selector": "#ad-ext-game-variant",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 153,
    "fn": "querySelector"
  },
  {
    "selector": ".showAnimations",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 157,
    "fn": "querySelector"
  },
  {
    "selector": ".showAnimations",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 158,
    "fn": "querySelector"
  },
  {
    "selector": "button[aria-label='Live mode']",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 291,
    "fn": "waitForElement"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 400,
    "fn": "waitForElement"
  },
  {
    "selector": "button",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 407,
    "fn": "querySelectorAll"
  },
  {
    "selector": "div",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 415,
    "fn": "querySelector"
  },
  {
    "selector": "div",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 422,
    "fn": "querySelectorAll"
  },
  {
    "selector": "#ad-ext-turn",
    "file": "entrypoints/match.content/Zoom.vue",
    "line": 462,
    "fn": "querySelector"
  },
  {
    "selector": "[data-slot]",
    "file": "utils/selectors.ts",
    "line": 55,
    "fn": "querySelector"
  },
  {
    "selector": "[class*='chakra-']",
    "file": "utils/selectors.ts",
    "line": 56,
    "fn": "querySelector"
  },
  {
    "selector": "Lobby",
    "file": "utils/selectors.ts",
    "line": 202,
    "fn": "waitForElementWithTextContent"
  },
  {
    "selector": "img[src^=\\\"blob:\\\"]",
    "file": "utils/websocket-helpers.ts",
    "line": 263,
    "fn": "querySelectorAll"
  }
];
